name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker login -u gomonuk -p ${{ secrets.DOCKERHUB_TOKEN }} && docker build . --file Dockerfile --tag gomonuk/calcbot:latest && docker push gomonuk/calcbot:latest
